### ISSUE TITLE
A few issues in time-depedent ops docs

### ISSUE THREAD

**Issue by amilsted** [qojulia/QuantumOptics.jl-documentation#13]
https://docs.qojulia.org/timeevolution/timedependent-problems/ has examples that appear to be rendered incorrectly. Also I erroneously wrote "in code" prior to a latex formula.

**Comment by amilsted** [comment]
Also, docstring were not properly pulled in: https://docs.qojulia.org/api/#API:-Quantum-objects-types

**Comment by Lightup1** [comment]
`TimeDepedentSum(1.0=>H_static, cos=>H_drive1, t->10.0 * sin(5*t)=>H_drive2)`
`TimeDepedentSum` should be `TimeDependentSum`
`t->10.0 * sin(5*t)=>H_drive2` should be `(t->10.0 * sin(5*t))=>H_drive2`
