### ISSUE TITLE
The copyright banner is overlapping lower part documentation

### ISSUE THREAD

**Issue by cbcoutinho** [qojulia/QuantumOptics.jl-documentation#5]
The copyright banner is overlapping the bottom of the documentation on my laptop. This covers the 'Previous' and 'Next' buttons. It's not a terrible issue, but I thought you would like to know about it.

**Comment by bastikr** [comment]
Thank you very much for taking the time to inform us! We will fix this soon.

**Comment by lostermann** [comment]
Fixed via CSS correction in Website-Repo.
